[package]
name = "vproxy"
version = "0.1.0"
authors = ["Gui Vieira <guialbuk@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
diesel = { version = "1.4.7", features = ["chrono", "postgres"] }
dotenv = "0.15.0"
rocket = "0.5.0-rc.1"
